# frozen_string_literal: true

# v0.11.0 — Admin endpoints for the custodial-wallet system.
#
# GET  /admin/coin-engine/wallets/status.json
#   Returns counts and config state so the admin UI can render the backfill
#   banner: how many users need a wallet, whether autogen is enabled, whether
#   the encryption passphrase is set.
#
# POST /admin/coin-engine/wallets/backfill.json
#   Enqueues CoinEngineGenerateWallet for every user without a wallet field
#   AND without an existing custodial row. Staggered (50/sec) to avoid burst.
#   Returns the number of jobs enqueued.
#
# POST /admin/coin-engine/wallets/regenerate.json   (body: { user_id })
#   Force a fresh keypair for one user. Only used when an admin wants to roll
#   a wallet that was leaked (the prior custodial row is marked revoked).

module DiscourseCoinEngine
  class AdminWalletsController < ::Admin::AdminController
    requires_login
    before_action :ensure_admin

    BACKFILL_HARD_CAP = 5_000   # safety: never enqueue more than this in one click
    BATCH_SIZE        = 50      # how many jobs share a 1-second bucket
    THROTTLE_KEY      = 'coin_engine_wallet_backfill_last_at'.freeze

    rescue_from ActiveRecord::RecordInvalid do |e|
      render json: { errors: e.record.errors.full_messages }, status: 422
    end

    rescue_from ::Discourse::InvalidParameters do |e|
      render json: { errors: [e.message] }, status: 400
    end

    def status
      render json: {
        autogen_enabled:  !!(SiteSetting.coin_engine_wallet_autogen_enabled rescue false),
        passphrase_set:   ::DiscourseCoinEngine::WalletEncryption.passphrase_set?,
        users_missing:    users_missing_wallet_count,
        custodial_count:  ::DiscourseCoinEngine::CustodialWallet.active.count,
        last_backfill_at: Rails.cache.read(THROTTLE_KEY),
        hard_cap:         BACKFILL_HARD_CAP,
      }
    end

    def backfill
      unless ::DiscourseCoinEngine::WalletEncryption.passphrase_set?
        return render json: {
          errors: ['Set coin_engine_wallet_encryption_passphrase before running a backfill. Without it the job no-ops every user.']
        }, status: 503
      end

      # Throttle: max one backfill kick every 5 minutes (the previous run will
      # likely still be draining its queue anyway). Admin can force.
      last = Rails.cache.read(THROTTLE_KEY)
      force = ActiveModel::Type::Boolean.new.cast(params[:force])
      if !force && last && Time.now - last < 5.minutes
        wait = (5.minutes - (Time.now - last)).to_i
        return render json: { errors: ["Backfill ran #{(Time.now - last).to_i}s ago. Wait #{wait}s or pass force=true."] }, status: 429
      end

      ids = users_missing_wallet_ids(limit: BACKFILL_HARD_CAP)

      ids.each_with_index do |uid, i|
        # Stagger 50 jobs per second so the worker pool isn't slammed and we
        # don't blow through the SidekiqQueue's per-second push budget.
        delay = (i / BATCH_SIZE).seconds
        ::Jobs.enqueue_in(delay, :coin_engine_generate_wallet, user_id: uid, source: 'backfill_server')
      end

      Rails.cache.write(THROTTLE_KEY, Time.now, expires_in: 1.day)
      Rails.logger.info("[coin_engine] wallet backfill enqueued #{ids.size} jobs by admin #{current_user.username}")

      render json: { ok: true, enqueued: ids.size, hard_cap_hit: ids.size >= BACKFILL_HARD_CAP }
    end

    def regenerate
      uid = params[:user_id].to_i
      raise ::Discourse::InvalidParameters, 'user_id' if uid <= 0

      user = ::User.find_by(id: uid)
      raise ::Discourse::NotFound unless user

      unless ::DiscourseCoinEngine::WalletEncryption.passphrase_set?
        return render json: { errors: ['Encryption passphrase not configured.'] }, status: 503
      end

      # Mark any existing custodial row revoked so the audit trail captures the
      # roll. The job's idempotency check looks for active rows only, so a
      # revoked row will not block the new generation.
      old = ::DiscourseCoinEngine::CustodialWallet.find_by(user_id: uid, revoked_at: nil)
      if old
        old.update!(
          revoked_at: Time.zone.now,
          revoked_reason: "regenerated by admin @#{current_user.username}: #{params[:reason].to_s.strip[0, 200].presence || 'unspecified'}",
        )
      end

      # Clear the user_field so the job picks the user up via the empty-field path
      field_id = (SiteSetting.coin_engine_solana_wallet_user_field_id rescue 1).to_i
      ::UserCustomField.where(user_id: uid, name: "user_field_#{field_id}").delete_all

      ::Jobs.enqueue(:coin_engine_generate_wallet, user_id: uid, source: 'admin_regen')
      render json: { ok: true, queued: true, revoked_old: !!old }
    end

    private

    def users_missing_wallet_ids(limit:)
      field_id = (SiteSetting.coin_engine_solana_wallet_user_field_id rescue 1).to_i
      sql = <<~SQL
        SELECT u.id
          FROM users u
          LEFT JOIN user_custom_fields ucf
            ON ucf.user_id = u.id AND ucf.name = 'user_field_#{field_id}'
          LEFT JOIN coin_engine_custodial_wallets cw
            ON cw.user_id = u.id AND cw.revoked_at IS NULL
         WHERE u.id > 0
           AND u.active = TRUE
           AND u.staged = FALSE
           AND u.suspended_at IS NULL
           AND (ucf.value IS NULL OR TRIM(ucf.value) = '')
           AND cw.id IS NULL
         ORDER BY u.id ASC
         LIMIT #{limit.to_i}
      SQL
      ::ActiveRecord::Base.connection.select_values(sql).map(&:to_i)
    rescue StandardError => e
      Rails.logger.error("[coin_engine] users_missing_wallet_ids failed: #{e.class}: #{e.message}")
      []
    end

    def users_missing_wallet_count
      field_id = (SiteSetting.coin_engine_solana_wallet_user_field_id rescue 1).to_i
      sql = <<~SQL
        SELECT COUNT(*)
          FROM users u
          LEFT JOIN user_custom_fields ucf
            ON ucf.user_id = u.id AND ucf.name = 'user_field_#{field_id}'
          LEFT JOIN coin_engine_custodial_wallets cw
            ON cw.user_id = u.id AND cw.revoked_at IS NULL
         WHERE u.id > 0
           AND u.active = TRUE
           AND u.staged = FALSE
           AND u.suspended_at IS NULL
           AND (ucf.value IS NULL OR TRIM(ucf.value) = '')
           AND cw.id IS NULL
      SQL
      ::ActiveRecord::Base.connection.select_value(sql).to_i
    rescue StandardError => e
      Rails.logger.error("[coin_engine] users_missing_wallet_count failed: #{e.class}: #{e.message}")
      -1
    end
  end
end
